name: playlist_annotator
description: Annotate songs from your Spotify playlists.

publish_to: 'none'
version: 0.0.1+1


environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  # own packages
  log:
    path: ./packages/log

  cupertino_icons: ^1.0.2

  get: ^4.6.6  
  http: ^1.1.0
  flutter_custom_tabs: ^1.2.1
  pocketbase: ^0.17.0
  secure_shared_preferences: ^0.0.4
  google_fonts: ^6.1.0
  skeletonizer: ^1.0.0
  share_plus: ^7.2.1
  url_launcher: ^6.2.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1


flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700